### ISSUE TITLE
Flutter package outdated

### ISSUE THREAD

**Issue by cervonwong** [microsoft/fluentui-system-icons#108]
This repository is in v1.1.72, but the flutter package (https://pub.dev/packages/fluentui_system_icons) is on 1.1.54.

Most of the icons have the old name or does not exist :(

**Comment by jamesblasco** [comment]
Until this and https://github.com/microsoft/fluentui-system-icons/issues/117 are fixed feel free to use this patch in your project:

```yaml
  fluentui_system_icons: 
    git: 
      url: https://github.com/jamesblasco/fluentui-system-icons/
      path: flutter/
      ref: patch-1
```
